### ISSUE TITLE
Why this requires promise

### ISSUE THREAD

**Issue by vko-online** [npm/uid-number#5]
i have this method

```
exports.send_sms = function(phone, done){
    uidNumber(phone, function (err, uid, gid) {
        if(err) {
            done(err, null);
        } else {
            done(null, uid);
        }
    });
};
```

Why this can't be just used as `uidNumber.get_uid()` ?

**Comment by isaacs** [comment]
I'm not sure what that method is doing.  This module is for getting a uid from a username.

**Comment by knoxcard** [comment]
Right, there must be a misunderstanding on @vko-online's behalf.

Close ticket?
